# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FuvdjunlmvL8PZIHl2SJ5O_GJGA7za48
"""

#POKEDEX
import requests
import json
import os

def get_pokemon_data(pokemon_name):
  """Obtiene los datos de un Pokémon desde la PokeAPI."""
  url = f"https://pokeapi.co/api/v2/pokemon/{pokemon_name.lower()}"
  response = requests.get(url)

  if response.status_code == 200:
    data = response.json()
    return data
  else:
    return None

def display_pokemon_info(pokemon_data):
  """Muestra la información del Pokémon."""
  if pokemon_data:
    print(f"Nombre: {pokemon_data['name'].capitalize()}")
    print(f"Peso: {pokemon_data['weight']}")
    print(f"Altura: {pokemon_data['height']}")

    print("\nTipos:")
    for type_data in pokemon_data['types']:
      print(f"- {type_data['type']['name'].capitalize()}")

    print("\nHabilidades:")
    for ability_data in pokemon_data['abilities']:
      print(f"- {ability_data['ability']['name'].capitalize()}")

    print("\nMovimientos:")
    for move_data in pokemon_data['moves']:
      print(f"- {move_data['move']['name'].capitalize()}")

    image_url = pokemon_data['sprites']['front_default']
    if image_url:
      print(f"\nImagen: {image_url}")
      # Puedes usar una librería como IPython.display para mostrar la imagen en Colab
      # from IPython.display import Image
      # display(Image(url=image_url))
    else:
      print("\nImagen no disponible.")

    return image_url
  else:
    print("Pokémon no encontrado.")
    return None

def save_pokemon_data(pokemon_data, image_url):
    """Guarda los datos del Pokémon en un archivo JSON."""
    if pokemon_data:
        pokemon_name = pokemon_data['name']
        if not os.path.exists('pokedex'):
            os.makedirs('pokedex')

        pokemon_info = {
            'name': pokemon_data['name'],
            'weight': pokemon_data['weight'],
            'height': pokemon_data['height'],
            'types': [type_data['type']['name'] for type_data in pokemon_data['types']],
            'abilities': [ability_data['ability']['name'] for ability_data in pokemon_data['abilities']],
            'moves': [move_data['move']['name'] for move_data in pokemon_data['moves']],
            'image_url': image_url
        }

        with open(f'pokedex/{pokemon_name}.json', 'w') as f:
            json.dump(pokemon_info, f, indent=4)
        print(f"Datos de {pokemon_name} guardados en pokedex/{pokemon_name}.json")

if __name__ == "__main__":
    print("Bienvenido a la Pokedex!")

    while True:
        pokemon_name = input("Introduce el nombre del Pokémon (o presiona 's' para salir): ")
        if pokemon_name.lower() == 's':
            break

        pokemon_data = get_pokemon_data(pokemon_name)
        image_url = display_pokemon_info(pokemon_data)
        if image_url:
            save_pokemon_data(pokemon_data, image_url)